site_name: PluvioTech
site_description: Red comunitaria de monitoreo de aluviones en San José de Maipo
site_author: PluvioTech
repo_url: https://github.com/CesarHD3000/capstone-2026-fluvio-tech
repo_name: capstone-2026-fluvio-tech

docs_dir: docs
site_dir: site

theme:
  name: material
  language: es
  logo: material/weather-pouring
  favicon: material/water
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: slate
      primary: custom
      accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list

plugins:
  - search

nav:
  - Inicio: index.md
  - Bitácora:
      - Guía de Bitácora: bitacora/GuíaBítacora.md
      - Sesión 1 (S01): bitacora/S01.md
  - Fases del Proyecto:
      - Fase 0 - Arranque: bitacora/Fases/Fase0.md
      - Fase 1: bitacora/Fases/Fase1.md
      - Fase 2: bitacora/Fases/Fase2.md
      - Fase 3: bitacora/Fases/Fase3.md
